spring.application.name=step4_mybatis

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ssafydb
spring.datasource.username=ssafy
spring.datasource.password=ssafy

spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=600000

mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.ssafy.shopApp.**.dto

logging.level.com.ssafy=trace

