spring.application.name=step3_mvc-1

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

db.datasoruce.driver.class.name=com.mysql.cj.jdbc.Driver
db.datasoruce.url=jdbc:mysql://127.0.0.1:3306/ssafydb
db.datasoruce.user=ssafy
db.datasoruce.password=ssafy